# Generated by Django 5.1.15 on 2026-08-16 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('items', '0001_initial'),
        ('projects', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('quarry_receipt', 'Quarry Production Receipt'), ('purchase_receipt', 'Purchase Receipt (GRN)'), ('transfer_in', 'Internal Transfer In'), ('transfer_out', 'Internal Transfer Out'), ('issue', 'Issue'), ('return', 'Return'), ('adjustment_in', 'Stock Count Adjustment (Increase)'), ('adjustment_out', 'Stock Count Adjustment (Decrease)')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit at time of transaction.', max_digits=14, null=True)),
                ('meter_reading', models.DecimalField(blank=True, decimal_places=1, help_text='Equipment hour-meter/odometer reading at time of a fuel dispense.', max_digits=12, null=True)),
                ('reference', models.CharField(blank=True, help_text='Transfer note / GRN / stock-take reference number.', max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('cost_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='projects.costcode')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, help_text='Set when this is a fuel or spare-part issue against a specific unit.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='fleet.equipment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='items.item')),
                ('related_transaction', models.ForeignKey(blank=True, help_text='Links a TRANSFER_OUT row to its paired TRANSFER_IN row at the destination store.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stock.stocktransaction')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='warehouses.store')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='fleet.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item', 'store'], name='stock_stock_item_id_96f10b_idx'), models.Index(fields=['cost_code'], name='stock_stock_cost_co_7cd364_idx'), models.Index(fields=['equipment'], name='stock_stock_equipme_121521_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_transaction_quantity_positive'), models.CheckConstraint(condition=models.Q(models.Q(('transaction_type__in', ['issue', 'adjustment_out']), _negated=True), ('cost_code__isnull', False), _connector='OR'), name='stock_transaction_issue_requires_cost_code')],
            },
        ),
    ]
