# Generated by Django 5.1.15 on 2026-08-16 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_tag', models.CharField(help_text='e.g. EXC-0142', max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('equipment_class', models.CharField(help_text='e.g. Excavator, Dump Truck, Grader, Asphalt Paver', max_length=64)),
                ('meter_type', models.CharField(choices=[('hours', 'Hour meter'), ('odometer', 'Odometer')], default='hours', max_length=16)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel (AGO)'), ('petrol', 'Petrol (PMS)'), ('electric', 'Electric'), ('none', 'None (non-powered)')], default='diesel', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_maintenance', 'Under Maintenance'), ('decommissioned', 'Decommissioned')], default='active', max_length=20)),
                ('current_meter_reading', models.DecimalField(decimal_places=1, default=0, max_digits=12)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_created', to=settings.AUTH_USER_MODEL)),
                ('home_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_equipment', to='warehouses.store')),
            ],
            options={
                'verbose_name_plural': 'equipment',
                'ordering': ['asset_tag'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_type', models.CharField(choices=[('breakdown', 'Breakdown'), ('preventive_maintenance', 'Preventive Maintenance')], max_length=24)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cost_code', models.ForeignKey(blank=True, help_text='Set if this job is billable to a project; leave blank for routine plant-overhead maintenance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='projects.costcode')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='fleet.equipment')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
