# Generated by Django 5.1.15 on 2026-08-16 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('aggregate', 'Aggregate (quarried material)'), ('fuel', 'Diesel / Fuel'), ('spare_part', 'Spare Part'), ('consumable', 'Consumable'), ('tool', 'Tool')], max_length=16)),
                ('unit_of_measure', models.CharField(help_text='e.g. tonne, litre, piece', max_length=16)),
                ('valuation_method', models.CharField(choices=[('weighted_average', 'Weighted Average'), ('standard_cost', 'Standard Cost')], default='weighted_average', max_length=20)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
    ]
