# Generated by Django 5.1.15 on 2026-08-16 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('user_created', 'User Created'), ('password_changed', 'Password Changed'), ('project_created', 'Project Created'), ('cost_code_created', 'Cost Code Created'), ('store_created', 'Store Created'), ('item_created', 'Item Created'), ('equipment_created', 'Equipment Created'), ('work_order_opened', 'Work Order Opened'), ('work_order_closed', 'Work Order Closed'), ('quarry_production_logged', 'Quarry Production Logged'), ('purchase_receipt', 'Purchase Receipt'), ('internal_transfer', 'Internal Transfer'), ('stock_issue', 'Stock Issue'), ('stock_return', 'Stock Return'), ('stock_adjustment', 'Stock Adjustment'), ('stock_count_recorded', 'Stock Count Recorded'), ('purchase_requisition_created', 'Purchase Requisition Created'), ('purchase_order_created', 'Purchase Order Created')], max_length=32)),
                ('description', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'audit log entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
