# Generated by Django 5.1.15 on 2026-08-16 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='e.g. LAG-EPE-01', max_length=32, unique=True)),
                ('store_type', models.CharField(choices=[('central_depot', 'Central Depot'), ('state_depot', 'State / Regional Depot'), ('project_site_store', 'Project Site Store'), ('quarry_stockyard', 'Quarry Stockyard')], max_length=32)),
                ('country', models.CharField(choices=[('NG', 'Nigeria'), ('TG', 'Togo'), ('BJ', 'Benin')], default='NG', max_length=2)),
                ('state_or_region', models.CharField(help_text='Nigerian state, or region within Togo/Benin', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_stores', to='warehouses.store')),
                ('project', models.ForeignKey(blank=True, help_text='Set for a project site store; blank for a central/state depot or quarry stockyard.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='projects.project')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Quarry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('NG', 'Nigeria'), ('TG', 'Togo'), ('BJ', 'Benin')], default='NG', max_length=2)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('licensed_material_types', models.CharField(blank=True, help_text="Comma-separated, e.g. 'granite, laterite, sand'", max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarries_created', to=settings.AUTH_USER_MODEL)),
                ('stockyard', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='quarry', to='warehouses.store')),
            ],
            options={
                'verbose_name_plural': 'quarries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='warehouses.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'user'), name='unique_store_assignment')],
            },
        ),
    ]
